namespace KismetAnalyzer;

using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

using System;
using System.Text;
using System.Reflection;
using System.Diagnostics;

using UAssetAPI;
using UAssetAPI.Unversioned;
using UAssetAPI.UnrealTypes;
using UAssetAPI.ExportTypes;
using UAssetAPI.PropertyTypes.Objects;
using UAssetAPI.PropertyTypes.Structs;
using UAssetAPI.Kismet.Bytecode;
using UAssetAPI.Kismet.Bytecode.Expressions;

using Dot;

using Konsole;
using System.Runtime.InteropServices;

public class Program
{
    static int Main(string[] args)
    {
        var rootCommand = new RootCommand();

        var assetSource = new Argument<string>
            (name: "src",
            description: "Source asset");
        var assetDestination = new Argument<string>
            (name: "dest",
            description: "Destination asset");
        var assetMerged = new Argument<string>
            (name: "merged",
            description: "Merged asset");
        var importIndexes = new Argument<IList<int>>
            (name: "import indexes",
            description: "Import indexes");
        var assetInput = new Argument<string>
            (name: "input",
            description: "Path to asset");
        var assetOutput = new Argument<string>
            (name: "output",
            description: "Path to asset");
        var assetInputDirectory = new Argument<string>
            (name: "input",
            description: "Path to asset input directory");
        var assetOutputDirectory = new Argument<string>
            (name: "output",
            description: "Path to asset output directory");
        var cfgOutputDiretory = new Argument<string>
            (name: "output",
            description: "Path to CFG output directory");
        var jsonOutput = new Argument<string>
            (name: "output",
            description: "Path to JSON output");
        var jsonInput = new Argument<string>
            (name: "input",
            description: "Path to JSON input");
        var jsonOutputDiretory = new Argument<string>
            (name: "output",
            description: "Path to JSON output directory");
        var contextPath = new Argument<string>
            (name: "context",
            description: "Path to context JSON object generated by BPGen plugin (kismet.json in UE project directory)");
        var showProgress = new Option<bool>
            (name: "--progress",
            description: "Show progress bar (possibly hides error messages)");
        var dotPath = new Option<string>
            (name: "--dot",
            description: "Path to graphviz dot executable, otherwise will search PATH");
        dotPath.AddValidator(result =>
        {
            if (!File.Exists(result.GetValueForOption(dotPath)))
            {
                result.ErrorMessage = "--dot path does not exist";
            }
        });

        var projectName = new Argument<string>
            (name: "project-name",
            description: "Unreal Engine project name (top level directory name in a game .pak)");
        var ueVersion = new Option<EngineVersion>
            (name: "--ue-version",
             description: "Unreal Engine version",
             getDefaultValue: () => EngineVersion.VER_UE4_27);
        var mappings = new Option<string>
            (name: "--mappings",
             description: "Path to .usmap for assets using unversioned properties");
        mappings.AddAlias("-m");

        rootCommand.AddGlobalOption(ueVersion);
        rootCommand.AddGlobalOption(mappings);

        var cfg = new Command("cfg", "Generate control flow graphs of single asset and open in a web browser");
        cfg.Add(assetInput);
        cfg.Add(dotPath);
        cfg.SetHandler(Cfg, ueVersion, mappings, assetInput, dotPath);
        rootCommand.AddCommand(cfg);

        var genCfg = new Command("gen-cfg", "Generate control flow graphs of single asset");
        genCfg.Add(assetInput);
        genCfg.Add(cfgOutputDiretory);
        genCfg.SetHandler(GenCfg, ueVersion, mappings, assetInput, cfgOutputDiretory);
        rootCommand.AddCommand(genCfg);

        var genCfgTree = new Command("gen-cfg-tree", "Generate control flow graphs of assets");
        genCfgTree.Add(assetInputDirectory);
        genCfgTree.Add(cfgOutputDiretory);
        genCfgTree.Add(projectName);
        genCfgTree.Add(dotPath);
        genCfgTree.Add(showProgress);
        genCfgTree.SetHandler(GenCfgTree, ueVersion, mappings, assetInputDirectory, cfgOutputDiretory, projectName, dotPath, showProgress);
        rootCommand.AddCommand(genCfgTree);

        var genJsonTree = new Command("gen-json-tree", "Generate JSON representation of assets");
        genJsonTree.Add(assetInputDirectory);
        genJsonTree.Add(jsonOutputDiretory);
        genJsonTree.SetHandler(GenJsonTree, ueVersion, mappings, assetInputDirectory, jsonOutputDiretory);
        rootCommand.AddCommand(genJsonTree);

        var toJson = new Command("to-json", "Convert binary asset to JSON");
        toJson.Add(assetInput);
        toJson.SetHandler(ToJson, ueVersion, mappings, assetInput);
        rootCommand.AddCommand(toJson);

        var read = new Command("read", "Read asset into memory");
        read.Add(assetInput);
        read.SetHandler(Read, ueVersion, mappings, assetInput);
        rootCommand.AddCommand(read);

        var fromJson = new Command("from-json", "Convert JSON to binary asset");
        fromJson.Add(assetOutput);
        fromJson.SetHandler(FromJson, ueVersion, mappings, assetOutput);
        rootCommand.AddCommand(fromJson);

        var copyImports = new Command("copy-imports", "Copies imports from one asset to another and returns the new import indexes");
        copyImports.Add(assetSource);
        copyImports.Add(assetDestination);
        copyImports.Add(importIndexes);
        copyImports.SetHandler(CopyImports, ueVersion, mappings, assetSource, assetDestination, importIndexes);
        rootCommand.AddCommand(copyImports);

        var mergeFunctions = new Command("merge-functions",
@"Merge functions from source asset to the start of functions with matching names in the destination asset.
Leading underscores can be used to work around special function names being illegal in the editor.");
        mergeFunctions.Add(assetSource);
        mergeFunctions.Add(assetDestination);
        mergeFunctions.Add(assetMerged);
        mergeFunctions.SetHandler(MergeFunctions, ueVersion, mappings, assetSource, assetDestination, assetMerged);
        rootCommand.AddCommand(mergeFunctions);

        new CommandLineBuilder(rootCommand)
           .UseVersionOption()
           .UseHelp()
           .UseEnvironmentVariableDirective()
           .UseParseDirective()
           .UseSuggestDirective()
           .UseTypoCorrections()
           .UseParseErrorReporting()
           .UseExceptionHandler()
           .CancelOnProcessTermination()
           .Build()
           .Invoke(args);

        return 0;
    }
    static IEnumerable<string> GetAssets(string directory)
    {
        var enumOptions = new EnumerationOptions();
        enumOptions.IgnoreInaccessible = true;
        enumOptions.RecurseSubdirectories = true;
        return new[] { "*.uasset", "*.umap" }.SelectMany(pattern => Directory.EnumerateFiles(directory, pattern, enumOptions));
    }
    static UAsset LoadAsset(EngineVersion ueVersion, string? mappings, string assetPath)
    {
        return mappings != null ? new UAsset(assetPath, ueVersion, new Usmap(mappings)) : new UAsset(assetPath, ueVersion);
    }
    static void WriteDotViewer(string dot, string outputPath, string? dotPath)
    {
        ProcessStartInfo info = new ProcessStartInfo(dotPath ?? "dot");
        info.RedirectStandardInput = true;
        info.RedirectStandardOutput = true;
        info.ArgumentList.Add("-Tsvg");
        var p = Process.Start(info) ?? throw new Exception("Process null");

        p.Start();

        p.StandardInput.Write(dot);
        p.StandardInput.Close();

        var svgData = p.StandardOutput.ReadToEnd();

        p.WaitForExit();

        var assembly = Assembly.GetAssembly(typeof(Program))!;
        var resourceName = $"{assembly.GetName().Name!.Replace("-", "_")}.viz.embed.html";
        var template = new StreamReader(assembly.GetManifestResourceStream(resourceName)!).ReadToEnd();
        var html = template.Replace("[DATA]", Convert.ToBase64String(Encoding.UTF8.GetBytes(svgData)));

        using (StreamWriter writetext = new StreamWriter(outputPath))
        {
            writetext.Write(html);
        }
    }
    static void Cfg(EngineVersion ueVersion, string? mappings, string assetPath, string? dotPath)
    {
        UAsset asset = LoadAsset(ueVersion, mappings, assetPath);

        var dot = new StringWriter();
        new SummaryGenerator(asset, StreamWriter.Null, dot).Summarize();

        string outputPath = Path.Join(System.IO.Path.GetTempPath(), $"{Path.GetFileNameWithoutExtension(assetPath)}-{Guid.NewGuid().ToString()}.html");
        WriteDotViewer(dot.ToString(), outputPath, dotPath);
        Console.WriteLine($"writing to {outputPath}");

        OpenUrl(outputPath);
    }
    static void GenCfg(EngineVersion ueVersion, string? mappings, string assetPath, string outputDir)
    {
        UAsset asset = LoadAsset(ueVersion, mappings, assetPath);
        var fileName = Path.GetFileName(assetPath);
        var output = new StreamWriter(Path.Join(outputDir, Path.ChangeExtension(fileName, ".txt")));
        var dotOutput = new StreamWriter(Path.Join(outputDir, Path.ChangeExtension(fileName, ".dot")));
        new SummaryGenerator(asset, output, dotOutput).Summarize();
        output.Close();
        dotOutput.Close();
    }
    struct Progress
    {
        public ProgressBar Bar { get; set; }
        public TextWriter StdOut { get; set; }
        public TextWriter StdError { get; set; }
        public TextWriter NullOut { get; set; }
    }
    static void GenCfgTree(EngineVersion ueVersion, string? mappings, string assetInputDir, string output, string projectName, string? dotPath, bool showProgress)
    {
        Directory.CreateDirectory(output);

        var graph = new Graph("digraph");
        graph.GraphAttributes["rankdir"] = "LR";

        var assets = GetAssets(assetInputDir).ToList();
        Progress? progress = null;
        if (showProgress)
        {
            progress = new Progress
            {
                Bar = new ProgressBar(assets.Count()),
                StdOut = Console.Out,
                StdError = Console.Error,
                NullOut = new System.IO.StreamWriter(System.IO.Stream.Null),
            };
            Console.SetOut(progress.Value.NullOut);
            Console.SetError(progress.Value.NullOut);
        }

        var usmap = mappings != null ? new Usmap(mappings) : null;

        var i = 0;
        foreach (var assetPath in assets)
        {
            if (progress is Progress p2)
            {
                Console.SetOut(p2.StdOut);
                p2.Bar.Refresh(i++, $"Hierarchy... ({Path.GetFileName(assetPath)})");
                Console.SetOut(p2.NullOut);
            }
            var asset = new UAsset(assetPath, ueVersion, usmap);
            var classExport = asset.GetClassExport();
            if (classExport != null)
            {
                var parent = classExport.SuperStruct.ToImport(asset);

                var assetPackage = Path.Join("/Game", Path.GetRelativePath(Path.Join(assetInputDir, projectName, "Content"), Path.GetDirectoryName(assetPath)!), Path.GetFileNameWithoutExtension(assetPath));
                Console.WriteLine($"{assetPackage}.{classExport.ObjectName} : {parent.OuterIndex.ToImport(asset).ObjectName}.{parent.ObjectName}");
                var fullClassName = $"{assetPackage}.{classExport.ObjectName}";
                var fullParentName = $"{parent.OuterIndex.ToImport(asset).ObjectName}.{parent.ObjectName}";

                string relativePath = Path.GetRelativePath(assetInputDir, Path.GetDirectoryName(assetPath)!);
                string fileName = Path.ChangeExtension(Path.GetFileName(assetPath), ".html");

                var classNode = new Node(fullClassName);
                classNode.Attributes["label"] = classExport.ObjectName.ToString();
                classNode.Attributes["URL"] = Path.Join("cfgs", relativePath, fileName).Replace('\\', '/');
                graph.Nodes.Add(classNode);

                var edge = new Edge(fullClassName, fullParentName);
                graph.Edges.Add(edge);
            }
        }
        var hierarchyPath = Path.Join(output, "index.html");
        var hierarchy = new StringWriter();
        graph.Write(hierarchy);
        WriteDotViewer(hierarchy.ToString(), hierarchyPath, dotPath);

        i = 0;
        Parallel.ForEach(assets, assetPath =>
        {
            if (progress is Progress p2)
            {
                Console.SetOut(p2.StdOut);
                p2.Bar.Refresh(i++, $"CFGs... ({Path.GetFileName(assetPath)})");
                Console.SetOut(p2.NullOut);
            }
            var outputDir = Path.GetDirectoryName(Path.Join(output, "cfgs", Path.GetRelativePath(assetInputDir, assetPath)))!;
            var outputPath = Path.Join(outputDir, Path.ChangeExtension(Path.GetFileName(assetPath), ".html"));
            Directory.CreateDirectory(outputDir);

            UAsset asset = new UAsset(assetPath, ueVersion, usmap);

            var dot = new StringWriter();
            if (new SummaryGenerator(asset, TextWriter.Null, dot).Summarize())
            {
                WriteDotViewer(dot.ToString(), outputPath, dotPath);
            }
        });
        if (progress is Progress p3)
        {
            Console.SetOut(p3.StdOut);
            Console.SetError(p3.StdError);
            Console.WriteLine(); // wipe progress bar
        }
        Console.WriteLine($"Finished generating CFGs for {assets.Count()} assets");
    }
    static void GenJsonTree(EngineVersion ueVersion, string? mappings, string assetInputDir, string jsonOutputDir)
    {
        foreach (var assetPath in GetAssets(assetInputDir))
        {
            var outputPath = Path.ChangeExtension(Path.Join(jsonOutputDir, Path.GetRelativePath(assetInputDir, assetPath)), ".json");

            var asset = LoadAsset(ueVersion, mappings, assetPath);

            string jsonSerializedAsset = asset.SerializeJson(Newtonsoft.Json.Formatting.Indented);
            Console.WriteLine(outputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
            File.WriteAllText(outputPath, jsonSerializedAsset);
        }
    }
    static void ToJson(EngineVersion ueVersion, string? mappings, string assetInput)
    {
        Console.WriteLine(LoadAsset(ueVersion, mappings, assetInput).SerializeJson(Newtonsoft.Json.Formatting.Indented));
    }
    static void Read(EngineVersion ueVersion, string? mappings, string assetInput)
    {
        LoadAsset(ueVersion, mappings, assetInput);
        Console.WriteLine("complete");
    }
    static void FromJson(EngineVersion ueVersion, string? mappings, string assetOutput)
    {
        UAsset.DeserializeJson(Console.OpenStandardInput()).Write(assetOutput);
    }
    static void CopyImports(EngineVersion ueVersion, string? mappings, string assetSource, string assetDestination, IList<int> imports)
    {
        UAsset from = LoadAsset(ueVersion, mappings, assetSource);
        UAsset to = LoadAsset(ueVersion, mappings, assetDestination);

        foreach (var index in imports)
        {
            var newIndex = Kismet.CopyImportTo((from, FPackageIndex.FromRawIndex(index)), to)!;
            var i = newIndex.ToImport(to);
            Console.WriteLine($"Copied import {index} => {newIndex}: {i.ClassName}, {i.ClassPackage}, {i.ObjectName}");
        }

        to.Write(assetDestination);
    }
    static void MergeFunctions(EngineVersion ueVersion, string? mappings, string assetSource, string assetDestination, string assetMerged)
    {
        UAsset source = LoadAsset(ueVersion, mappings, assetSource);
        UAsset dest = LoadAsset(ueVersion, mappings, assetDestination);
        foreach (var export in source.Exports)
        {
            if (export is FunctionExport fnSrc)
            {
                if (export.ObjectName.ToString().StartsWith("ExecuteUbergraph"))
                {
                    Console.Error.WriteLine("Ignoring ubergraph");
                    continue;
                }
                var found = false;
                foreach (var exportDest in dest.Exports)
                {
                    if (exportDest is FunctionExport fnDest)
                    {
                        if (fnSrc.ObjectName.ToString().TrimStart('_') != fnDest.ObjectName.ToString().TrimStart('_')) continue;
                        Console.WriteLine($"Found matching function named {export.ObjectName}");

                        var newInst = new List<KismetExpression>();
                        //for (int i = 0; i < fnSrc.ScriptBytecode.Length; i++) {
                        var offset = 0;
                        var keepReturn = false;
                        foreach (var inst in fnSrc.ScriptBytecode)
                        {
                            if (inst is EX_Context c)
                            {
                                if (c.ContextExpression is EX_LocalVirtualFunction i)
                                {
                                    if (i.VirtualFunctionName.Value.ToString() == "RETURN")
                                    {
                                        keepReturn = true;
                                        continue; // TODO handle offset addresses in source function because now we're skipping expressions
                                    }
                                }
                            }
                            var isReturn = inst.GetType() == typeof(EX_Return);
                            if (isReturn ? keepReturn : true)
                            {
                                offset += (int)inst.GetSize(source);
                                newInst.Add(Kismet.CopyExpressionTo(inst, source, dest, fnSrc, fnDest)!);
                            }
                            if (isReturn) break;
                        }
                        foreach (var inst in fnDest.ScriptBytecode)
                        {
                            Kismet.ShiftAddressses(inst, offset);
                            newInst.Add(inst);
                        }
                        fnDest.ScriptBytecode = newInst.ToArray();

                        found = true;
                        break;
                    }
                }
                if (!found)
                {
                    Kismet.CopyExportTo((source, FPackageIndex.FromExport(source.Exports.IndexOf(export))), dest);
                }
            }
        }
        dest.Write(assetMerged);
    }

    // https://stackoverflow.com/a/43232486
    static void OpenUrl(string url)
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            url = url.Replace("&", "^&");
            Process.Start(new ProcessStartInfo(url) { UseShellExecute = true });
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            Process.Start("xdg-open", url);
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Process.Start("open", url);
        }
    }
}
